// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cppARorder
NumericVector cppARorder(NumericMatrix mat);
RcppExport SEXP _DSMapR_cppARorder(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(cppARorder(mat));
    return rcpp_result_gen;
END_RCPP
}
// e_divisivecpp
IntegerVector e_divisivecpp(NumericMatrix mat, int N, double P);
RcppExport SEXP _DSMapR_e_divisivecpp(SEXP matSEXP, SEXP NSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(e_divisivecpp(mat, N, P));
    return rcpp_result_gen;
END_RCPP
}
// cppcorrNeighbor
NumericVector cppcorrNeighbor(NumericMatrix mat);
RcppExport SEXP _DSMapR_cppcorrNeighbor(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(cppcorrNeighbor(mat));
    return rcpp_result_gen;
END_RCPP
}
// cpprunstest
NumericVector cpprunstest(NumericMatrix mat, std::string alternative);
RcppExport SEXP _DSMapR_cpprunstest(SEXP matSEXP, SEXP alternativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpprunstest(mat, alternative));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DSMapR_cppARorder", (DL_FUNC) &_DSMapR_cppARorder, 1},
    {"_DSMapR_e_divisivecpp", (DL_FUNC) &_DSMapR_e_divisivecpp, 3},
    {"_DSMapR_cppcorrNeighbor", (DL_FUNC) &_DSMapR_cppcorrNeighbor, 1},
    {"_DSMapR_cpprunstest", (DL_FUNC) &_DSMapR_cpprunstest, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DSMapR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
