# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppARorder <- function(mat) {
    .Call(`_DSMapR_cppARorder`, mat)
}

e_divisivecpp <- function(mat, N, P) {
    .Call(`_DSMapR_e_divisivecpp`, mat, N, P)
}

cppcorrNeighbor <- function(mat) {
    .Call(`_DSMapR_cppcorrNeighbor`, mat)
}

cpprunstest <- function(mat, alternative) {
    .Call(`_DSMapR_cpprunstest`, mat, alternative)
}

